---
styleguide: sourcelevel/linters#latest
engines:
  reek:
    enabled: true
    channel: latest
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
      - app/views/**/*
    config:
      languages:
        ruby:
          mass_threshold: 20
  eslint:
    enabled: true
    config:
      extensions:
      - .js
      - .es6
  fixme:
    enabled: true
    exclude_paths:
      - app/code_review/deprecated.yml
      - app/code_review/engines.yml
      - app/code_review/overrides.yml
  remark-lint:
    enabled: true
  rubocop:
    enabled: true
    channel: latest
  scss-lint:
    enabled: true
exclude_paths:
- .env.example
- bin
- config
- db
- public
- script
- test
- tmp
- vendor
